- name: "{{ ansible_role_name}}: Generate config for /interface"
  ansible.builtin.include_role:
    name: utils/interface
  when: intent.subinterface is defined

- name: "{{ ansible_role_name }}: Generate config for /network-instance"
  ansible.builtin.include_role:
    name: utils/network-instance
  when: intent.network_instance | type_debug == 'dict'

- name: "{{ ansible_role_name }}: Generate config for /routing-policy"
  ansible.builtin.include_role:
    name: utils/policy
  when: intent.routing_policy is defined

- set_fact:
    intent: {}
  when: intent is undefined # this may happen if a pb-run is partial, e.g. l2vpn only, and no services are defined, e.g. spines

## this task is pruning resources from the device that are not in the intent
- name: Generate Delete sets for implicit pruning
  vars:
    purge_exclude:
      network_instance:
        - mgmt # never purge mgmt network-instance
      interfaces:
        - mgmt0
      subinterface:
        - mgmt0.0
  set_fact:
    delete: "{{ delete + lookup('template', '{{item}}_purge.j2', template_vars=intent) | from_yaml }}"
    cacheable: true
  loop: "{{ purgeable }}"
  when:
    - purge
    - ansible_run_tags == ["all"] # need full intent to prune resources
    #  - intent[item] is mapping
    - item in (lookup('template', item + '_purge.j2', template_vars=intent))

## this task deletes resources that are explicitly tagged with '_state: deleted' in the intent
- name: Generate Delete sets for explicit pruning
  set_fact:
    delete: "{{ delete + lookup('template', '{{item}}_delete.j2', template_vars=intent) | from_yaml | default([], true) }}"
    cacheable: true
  loop: "{{ purgeable }}"

#- debug:
#    var: update
#- debug:
#    var: replace
#- debug:
#    var: delete

- name: "Update resources on {{inventory_hostname}}"
  nokia.srlinux.config:
    update: "{{ update }}"
    replace: "{{ replace }}"
    delete: "{{ delete }}"

- ansible.builtin.set_stats:
    data:
      network_instance: "{{ intent.network_instance |default({}, true) | length }}"
      subinterface: "{{ intent.subinterface | default({}, true) | length }}"
      routing_policy: "{{ intent.routing_policy | default({}, true) | length }}"
      sw_version: "{{ sw_version }}"
    per_host: yes
  when:
    - ansible_run_tags == ["all"]
