- name: Generate config for /routing-policy
  set_fact:
    replace: "{{ replace + lookup('template', template_file, template_vars=intent) | from_yaml }}"
    cacheable: true
  vars:
    template_file: "{{ platform + '/' + sw_version + '/policy.j2'}}"
