- name: Get role path
  ansible.builtin.set_fact:
    my_dir: "{{ role_path }}"

- name: Get template version
  vars:
    calling_path: "{{ my_dir }}" # cannot pass special var 'role_path' as this is replaced by the path of the called role
  ansible.builtin.include_role:
    name: utils/template-version

- name: Generate JSON-RPC data for /routing-policy
  ansible.builtin.set_fact:
    replace: "{{ replace + lookup('template', template_file, template_vars=intent) | from_yaml }}"
    cacheable: true
  vars:
    template_file: "{{ tpl_base.path + '/policy.j2'}}"
