- name: Check available template versions
  stat:
    path: "{{ role_path + '/templates/' + platform + '/' + item }}"
  register: dirs
  loop:
    - "{{ sw_version }}"
    - "{{ sw_version|regex_replace('(\\.\\d+$)', '') }}"
    - "{{ sw_version|regex_replace('(\\.\\d+\\.\\d+$)', '') }}"
    - "default"

- name: Set template version
  set_fact: 
    tpl_base: "{{ dirs.results[3].stat | combine(dirs.results[2].stat, dirs.results[1].stat, dirs.results[0].stat) }}"
  failed_when: not tpl_base.isdir

- name: Generate config for /routing-policy
  set_fact:
    replace: "{{ replace + lookup('template', template_file, template_vars=intent) | from_yaml }}"
    cacheable: true
  vars:
    template_file: "{{ tpl_base.path + '/policy.j2'}}"
