host_intent: {}
group_intent:
  srl:
    routing_policy:
      prefix_set:
        loopbacks:
          prefix: 
          - ip-prefix: 192.168.255.0/24 
            mask-length-range: "32..32"
        servers:
          prefix: 
            - ip-prefix: 10.0.0.0/8
              mask-length-range: "24..32"
      policy:
        export-loopbacks:
          default-action:
              policy-result: reject
          statement:
          - name: 1
            match:
              prefix-set: loopbacks
            action:
              policy-result: accept
        lo-and-servers:
          default-action: 
            policy-result: reject
          statement:
          - name: 10
            match:
              prefix-set: loopbacks
            action:
              policy-result: accept
          - name: 20
            match:
              prefix-set: servers
            action:
              policy-result: accept
        pass-all:
          default-action:
            policy-result: accept
          statement:
          - name: 1
            match:
              protocol: bgp
            action:
              policy-result: accept
        pass-evpn:
          default-action:
            policy-result: accept
          statement:
          - name: 1
            match:
              protocol: bgp-evpn
            action:
              policy-result: accept
