host_intent:
  clab-4l2s-l1:
    subinterface:
      ethernet-1/48.0:
        ipv4_address: 192.168.1.1/31
      ethernet-1/49.0:
        ipv4_address: 192.168.0.1/31
      system0.0:
        ipv4_address: 192.168.255.1/32
#      mgmt0.0:
  clab-4l2s-l2:
    subinterface:
      ethernet-1/48.0:
        ipv4_address: 192.168.1.3/31
      ethernet-1/49.0:
        ipv4_address: 192.168.0.3/31
      system0.0:
        ipv4_address: 192.168.255.2/32
#      mgmt0.0:
  clab-4l2s-l3:
    subinterface:
      ethernet-1/48.0:
        ipv4_address: 192.168.1.5/31
      ethernet-1/49.0:
        ipv4_address: 192.168.0.5/31
      system0.0:
        ipv4_address: 192.168.255.3/32
#      mgmt0.0:
  clab-4l2s-l4:    
    subinterface:
      ethernet-1/48.0:
        ipv4_address: 192.168.1.7/31
      ethernet-1/49.0:
        ipv4_address: 192.168.0.7/31
      system0.0:
        ipv4_address: 192.168.255.4/32
#      mgmt0.0:
  clab-4l2s-s1:
    subinterface:
      ethernet-1/1.0:
        ipv4_address: 192.168.0.0/31
      ethernet-1/2.0:
        ipv4_address: 192.168.0.2/31
      ethernet-1/3.0:
        ipv4_address: 192.168.0.4/31
      ethernet-1/4.0:
        ipv4_address: 192.168.0.6/31
      system0.0:
        ipv4_address: 192.168.255.101/32
#      mgmt0.0:
  clab-4l2s-s2:    
    subinterface:
      ethernet-1/1.0:
        ipv4_address: 192.168.1.0/31
      ethernet-1/2.0:
        ipv4_address: 192.168.1.2/31
      ethernet-1/3.0:
        ipv4_address: 192.168.1.4/31
      ethernet-1/4.0:
        ipv4_address: 192.168.1.6/31
      system0.0:
        ipv4_address: 192.168.255.102/32
#      mgmt0.0:

group_intent:
  leaf:
    interfaces:
      ethernet-1/1:
        admin_state: enable
        vlan_tagging: yes
      ethernet-1/2:
        admin_state: enable
        vlan_tagging: yes
      ethernet-1/3:
        admin_state: enable
        vlan_tagging: yes
      ethernet-1/4:
        admin_state: enable
        vlan_tagging: yes
      ethernet-1/48:
        description: "to_spine2_1/1"
        admin_state: enable
        _tag: isl
      ethernet-1/49:
        description: "to_spine1_1/1"
        admin_state: enable
        _tag: isl
      irb1:
#      mgmt0:
      system0:
        admin_state: enable
    subinterface:
      ethernet-1/1.0:
        type: bridged
        vlan: untagged
      ethernet-1/2.0:
        type: bridged
        vlan: untagged

      
#    tunnel_interface:
#      vxlan1: {}
  spine:
    interfaces:
      ethernet-1/1:
        admin_state: enable
        _tag: isl
      ethernet-1/2:
        admin_state: enable
        _tag: isl
      ethernet-1/3:
        admin_state: enable
        _tag: isl
      ethernet-1/4:
        admin_state: enable
        _tag: isl
      irb1:
#      mgmt0:
      system0:
        admin_state: enable

