- name: Get role path
  ansible.builtin.set_fact:
    my_dir: "{{ role_path }}"

- name: Get template version
  vars:
    calling_path: "{{ my_dir }}" # cannot pass special var 'role_path' as this is replaced by the path of the called role
  ansible.builtin.include_role:
    name: utils/template-version

- name: Generate JSON-RPC data for /system
  ansible.builtin.set_fact:
    update: "{{ update + lookup('template', template_file, template_vars=intent) | from_yaml }}"
    cacheable: true
  when: intent.system is defined and intent.system is not none
  vars:
    template_file: "{{ tpl_base.path + '/system.j2' }}"
