- name: Generate Delete sets
  vars:
    purge_exclude:
      network_instance: 
      - mgmt  # never purge mgmt network-instance
      interfaces:
      - mgmt0
      subinterface:
      - mgmt0.0
  set_fact:
    delete: "{{ delete + lookup('template', '{{item}}_purge.j2', template_vars=intent) | from_yaml }}"
    cacheable: true
  loop: "{{ purgeable }}"
  when:  
  - purge
  - item in (lookup('template', item + '_purge.j2', template_vars=intent))
