- set_fact:
    my_intent: {}

- name: "Load vars for ENV:{{ env }}"
  include_vars:
    dir: "{{ lookup('env', 'ENV') }}"

- name: "{{ ansible_role_name }}: Generate low-level intent for L3VPN"
  set_fact:
    my_intent: "{{ lookup('template', 'transform_l3vpn_intent.j2') | from_yaml }}"
  when: l3vpn is mapping

#- debug:
#    var:
#      my_intent

- set_fact:
    intent: "{{ intent | combine({'network_instance': my_intent.network_instance}, recursive=true, list_merge='append') }}"
  when: my_intent.network_instance is defined 

- set_fact:
    intent: "{{ intent | combine({'subinterface': my_intent.subinterface}, recursive=true) }}"
  when: my_intent.subinterface is defined

- set_fact:
    intent: "{{ intent | combine({'tunnel_interface': my_intent.tunnel_interface},recursive=true) }}"
  when: my_intent.tunnel_interface is defined

