- set_fact:
    my_intent: {}

- name: "Load vars for ENV:{{ env }}"
  include_vars:
    dir: "{{ lookup('env', 'ENV') }}"

- name: "{{ ansible_role_name }}: Generate low-level intent for L3VPN"
  set_fact:
    my_intent: "{{ lookup('template', 'transform_l3vpn_intent.j2') | from_yaml }}"
  when: l3vpn is mapping

- set_fact:
    intent: "{{ intent|default({}) | combine({'network_instance': my_intent.network_instance}, recursive=true, list_merge='append') }}"
  when:
    - my_intent is defined and my_intent is not none
    - my_intent.network_instance is defined and my_intent.network_instance is not none

- set_fact:
    intent: "{{ intent|default({}) | combine({'subinterface': my_intent.subinterface}, recursive=true) }}"
  when:
    - my_intent is defined and my_intent is not none
    - my_intent.subinterface is defined and my_intent.subinterface is not none

- set_fact:
    intent: "{{ intent|default({}) | combine({'tunnel_interface': my_intent.tunnel_interface},recursive=true) }}"
  when:
    - my_intent is defined and my_intent is not none
    - my_intent.tunnel_interface is defined and my_intent.tunnel_interface is not none
