- name: Generate config for /interface
  set_fact:
    update: "{{ update + lookup('template', template_file, template_vars=intent) | from_yaml }}"
    cacheable: true
  when: intent.interfaces is defined and intent.interfaces is mapping
  vars:
    template_file: "{{ sw_version + '/interface.j2'}}"

- name: Generate config for /interface/subinterface
  set_fact:
    replace: "{{ replace + lookup('template', template_file, template_vars=intent) | from_yaml }}"
    cacheable: true
  when: intent.subinterface is defined and intent.subinterface is mapping
  vars:
    template_file: "{{ sw_version + '/subinterface.j2'}}"  

- name: Generate config for /tunnel-interface
  set_fact:
    update: "{{ update + lookup('template', template_file, template_vars=intent) | from_yaml }}"
    cacheable: true
  when: intent.tunnel_interface is defined and intent.tunnel_interface is mapping
  vars:
    template_file: "{{ sw_version + '/tunnel.j2'}}"  
