- name: Get role path
  set_fact:
    my_dir: "{{ role_path }}"

- name: Get template version
  vars:
    calling_path: "{{ my_dir }}" # cannot pass special var 'role_path' as this is replaced by the path of the called role
  ansible.builtin.include_role:
    name: utils/template-version

- name: Generate config for /interface
  set_fact:
    update: "{{ update + lookup('template', template_file, template_vars=intent) | from_yaml }}"
    cacheable: true
  when: intent.interfaces is defined and intent.interfaces is not none
  vars:
    template_file: "{{ tpl_base.path + '/interface.j2' }}"

- name: Generate config for /interface/subinterface
  set_fact:
    replace: "{{ replace + lookup('template', template_file, template_vars=intent) | from_yaml | default([], true) }}"
    cacheable: true
  when: intent.subinterface is defined and intent.subinterface is not none
  vars:
    template_file: "{{ tpl_base.path + '/subinterface.j2'}}"

- name: Generate config for /tunnel-interface
  set_fact:
    update: "{{ update + lookup('template', template_file, template_vars=intent) | from_yaml | default([], true) }}"
    cacheable: true
  when: intent.tunnel_interface is defined and intent.tunnel_interface is not none
  vars:
    template_file: "{{ tpl_base.path + '/tunnel.j2'}}"
