- name: "Load Intent: /network-instance" 
  ansible.builtin.include_role:
    name: utils/load_intent

- set_fact:
    intent: "{{ intent | default({}) | combine(my_intent, recursive=true) }}"

- name: Generate config for /network-instance[name=default]
  ansible.builtin.include_role:
    name: utils/network-instance
