- name: "Load Intent: /network-instance" 
  ansible.builtin.include_role:
    name: utils/load_intent

- set_fact:
    network_instance: "{{ my_intent.network_instance }}"

- name: Generate config for /network-instance[name=default]
  ansible.builtin.include_role:
    name: utils/network-instance
