- name: init facts
  set_fact:
    update: []
    replace: []
    delete: []
    cacheable: true

- name: Get facts from device
  nokia.srlinux.get:
    paths:
      - path: /
        datastore: running
      - path: /platform/control[slot=A]/software-version
        datastore: state
      - path: /system/lldp/interface[name=*]/neighbor
        datastore: state
  register: res

- set_fact:
    running_config: "{{ res['result'][0] }}"
    sw_version: "{{ res['result'][1].split('-')[0] }}"
    lldp_nbrs: "{{ res.result[2].interface | items2dict(key_name='name', value_name='neighbor') }}"

- name: Check SR Linux version
  ansible.builtin.assert:
    that:
      - sw_version | regex_search('^v(\\d+)', '\\1') | map('int') | first  >= 23
    fail_msg: "Minimal SR Linux version is 23.3.1. Please upgrade your switches first"

- name: Check if 'ENV' environment var is set
  set_fact:
    env: "{{ lookup('env', 'ENV') | default('') }}"
  failed_when: env == ''
