- name: init facts
  set_fact:
    update: []
    replace: []
    delete: []
    cacheable: true

- name: load config from device
#  nokia_ni_cnpi.srlinux.srl_facts: {} # config in 'ansible_net_config' fact
  nokia.srl.jsonrpc_get:
    paths:
      - path: /
        datastore: running
  register: get_config

- set_fact:
    running_config: "{{ get_config['data']['result'][0] }}"
