- name: init facts
  set_fact:
    update: []
    replace: []
    delete: []
    cacheable: true

- name: Get facts from device
#  nokia_ni_cnpi.srlinux.srl_facts: {} # config in 'ansible_net_config' fact
  nokia.srl.jsonrpc_get:
    paths:
      - path: /
        datastore: running
      - path: /platform/control[slot=A]/software-version
        datastore: state
      - path: /system/lldp/interface[name=*]/neighbor
        datastore: state
  register: res

- set_fact:
    running_config: "{{ res['json']['result'][0] }}"
    sw_version: "{{ res['json']['result'][1].split('-')[0] }}"
    lldp_nbrs: "{{ res.json.result[2].interface | items2dict(key_name='name', value_name='neighbor') }}"

- name: Check if 'ENV' environment var is set
  set_fact:
    env: "{{ lookup('env', 'ENV') | default('') }}"
  failed_when: env == ''
