- name: init facts
  set_fact:
    update: []
    replace: []
    delete: []
    cacheable: true

- name: Get facts from device
#  nokia_ni_cnpi.srlinux.srl_facts: {} # config in 'ansible_net_config' fact
  nokia.srl.jsonrpc_get:
    paths:
      - path: /
        datastore: running
      - path: /platform/control[slot=A]/software-version
        datastore: state
  register: res

- set_fact:
    running_config: "{{ res['data']['result'][0] }}"
    sw_version: "{{ res['data']['result'][1].split('-')[0] }}"
