- name: "Load host vars for ENV:{{ env }}"
  ansible.builtin.include_vars:
    name: host_intent
    dir: "{{ playbook_dir + '/intent/' + env }}" # Load vars from files in 'dir'
    files_matching: "host_infra"

- name: "Load group vars for ENV:{{ env }}"
  ansible.builtin.include_vars:
    name: group_intent
    dir: "{{ playbook_dir + '/intent/' + env }}" # Load vars from files in 'dir'
    files_matching: "group_infra"

- name: Load group intent
  ansible.builtin.set_fact:
    intent: "{{ intent | default({}) | combine(group_intent[item], recursive=True) }}"
  loop: "{{ group_names }}"
  when: item in group_intent|default({}, true)

- name: Load nodal intent
  ansible.builtin.set_fact:
    intent: "{{ intent | default({}, true) | combine(host_intent[inventory_hostname], recursive=True) }}"
  when: inventory_hostname in host_intent|default({}, true)

- name: Generate itf descriptions
  when:
    - lldp_nbrs is defined
    - intent._features is defined and intent._features is not none
    - intent._features.auto_itf_desc is true
  block:
    - name: Generate itf descriptions from LLDP state
      ansible.builtin.set_fact:
        itf_desc: "{{ lookup('template', template_file, template_vars=intent) | from_yaml }}"
      vars:
        template_file: 'set_itf_desc.j2'

    - name: Update intent with generated itf descriptions
      ansible.builtin.set_fact:
        intent: "{{ intent | combine(itf_desc, recursive=true) }}"
