- name: "Load l2vpn intents for ENV:{{ env }}"
  include_vars:
    name: l2vpn
    dir: "{{ playbook_dir + '/intent/' + env }}" 
    files_matching: "l2vpn"

- name: "load l3vpn intents for ENV:{{ env }}"
  include_vars:
    name: l3vpn
    dir: "{{ playbook_dir + '/intent/' + env }}"
    files_matching: "l3vpn"
