- set_fact:
    my_intent: {}

- name: "{{ ansible_role_name }}: Generate low-level intent for L2VPN"
  set_fact:
    my_intent: "{{ lookup('template', 'transform_l2vpn_intent.j2') | from_yaml }}"
  when: l2vpn is defined and l2vpn is not none

- name: Update 'network_instance' in intent
  set_fact:
    intent: "{{ intent|default({}) | combine({'network_instance': my_intent.network_instance}, recursive=true) }}"
  when: my_intent.network_instance | type_debug == 'dict'

- name: Update 'subinterface' in intent
  set_fact:
    intent: "{{ intent|default({}) | combine({'subinterface': my_intent.subinterface}, recursive=true) }}"
  #  when: my_intent.subinterface is defined
  when: my_intent.subinterface is defined

- name: Update 'tunnel_interface' in intent
  set_fact:
    intent: "{{ intent|default({}) | combine({'tunnel_interface': my_intent.tunnel_interface},recursive=true) }}"
  when: my_intent.tunnel_interface is defined
