- name: "Load Intent: /interfaces" 
  ansible.builtin.include_role:
    name: utils/load_intent

- set_fact:
    intent: "{{ intent | default({}) | combine(my_intent, recursive=true) }}"

- name: Generate config for /interface
  ansible.builtin.include_role:
    name: utils/interface
  vars:
    intent: "{{ my_intent }}"